# Generated by Django 3.2.9 on 2021-12-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['-publishdate']},
        ),
    ]
