# Generated by Django 3.2.9 on 2021-12-30 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_machine_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('describtion', models.TextField()),
                ('publishdate', models.DateField(default=datetime.datetime.now)),
                ('photo', models.ImageField(upload_to='photos')),
            ],
            options={
                'ordering': ['-publishdate'],
            },
        ),
        migrations.DeleteModel(
            name='machine',
        ),
    ]
